-- Additive collections schema. Never modify or re-import the baseline in production.
CREATE TABLE IF NOT EXISTS payment_agreements (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 tenant_id BIGINT UNSIGNED NOT NULL,
 public_id CHAR(36) NOT NULL,
 lead_id BIGINT UNSIGNED NOT NULL,
 property_id BIGINT UNSIGNED NULL,
 created_by BIGINT UNSIGNED NOT NULL,
 project_name VARCHAR(160) NULL,
 property_title VARCHAR(255) NULL,
 currency CHAR(3) NOT NULL,
 modality VARCHAR(16) NOT NULL DEFAULT 'FIXED',
 total_price DECIMAL(18,2) NOT NULL,
 down_payment DECIMAL(18,2) NOT NULL,
 financed_balance DECIMAL(18,2) NOT NULL,
 monthly_rate_pct DECIMAL(7,4) NOT NULL DEFAULT 0,
 total_installments SMALLINT UNSIGNED NOT NULL,
 day_of_month_due TINYINT UNSIGNED NOT NULL,
 start_date DATE NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
 notes TEXT NULL,
 idempotency_key CHAR(36) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 UNIQUE KEY uq_agreement_public (public_id),
 UNIQUE KEY uq_agreement_scope (tenant_id,id),
 UNIQUE KEY uq_agreement_request (tenant_id,idempotency_key),
 KEY ix_agreement_lead (tenant_id,lead_id,status),
 FOREIGN KEY (tenant_id,lead_id) REFERENCES leads(tenant_id,id),
 FOREIGN KEY (tenant_id,property_id) REFERENCES properties(tenant_id,id),
 FOREIGN KEY (tenant_id,created_by) REFERENCES users(tenant_id,id),
 CHECK (currency IN ('ARS','USD')),
 CHECK (modality = 'FIXED'),
 CHECK (status IN ('ACTIVE','COMPLETED','CANCELLED')),
 CHECK (total_price > 0 AND down_payment >= 0 AND financed_balance = total_price - down_payment AND financed_balance > 0),
 CHECK (monthly_rate_pct >= 0 AND total_installments BETWEEN 1 AND 360 AND day_of_month_due BETWEEN 1 AND 31)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS installments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 tenant_id BIGINT UNSIGNED NOT NULL,
 public_id CHAR(36) NOT NULL,
 agreement_id BIGINT UNSIGNED NOT NULL,
 installment_number SMALLINT UNSIGNED NOT NULL,
 due_date DATE NOT NULL,
 amount_expected DECIMAL(18,2) NOT NULL,
 cancelled_at DATETIME(3) NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 UNIQUE KEY uq_installment_public (public_id),
 UNIQUE KEY uq_installment_scope (tenant_id,id),
 UNIQUE KEY uq_installment_number (tenant_id,agreement_id,installment_number),
 KEY ix_installment_due (tenant_id,due_date,id),
 FOREIGN KEY (tenant_id,agreement_id) REFERENCES payment_agreements(tenant_id,id),
 CHECK (amount_expected > 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS installment_payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 tenant_id BIGINT UNSIGNED NOT NULL,
 public_id CHAR(36) NOT NULL,
 installment_id BIGINT UNSIGNED NOT NULL,
 amount DECIMAL(18,2) NOT NULL,
 method VARCHAR(16) NOT NULL,
 receipt_number VARCHAR(120) NOT NULL,
 paid_at DATE NOT NULL,
 recorded_by BIGINT UNSIGNED NOT NULL,
 notes TEXT NULL,
 reversed_at DATETIME(3) NULL,
 reversed_by BIGINT UNSIGNED NULL,
 reversal_reason VARCHAR(500) NULL,
 idempotency_key CHAR(36) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 UNIQUE KEY uq_payment_public (public_id),
 UNIQUE KEY uq_payment_request (tenant_id,idempotency_key),
 KEY ix_payment_installment (tenant_id,installment_id,reversed_at),
 FOREIGN KEY (tenant_id,installment_id) REFERENCES installments(tenant_id,id),
 FOREIGN KEY (tenant_id,recorded_by) REFERENCES users(tenant_id,id),
 FOREIGN KEY (tenant_id,reversed_by) REFERENCES users(tenant_id,id),
 CHECK (amount > 0),
 CHECK (method IN ('TRANSFER','CASH','CHECK','DEPOSIT'))
) ENGINE=InnoDB;

INSERT IGNORE INTO schema_versions(version,description)
VALUES ('2026-09-08.001','Collections: agreements, installments and payment ledger');
