ALTER TABLE users DROP CHECK ck_users_role,
ADD CONSTRAINT ck_users_role CHECK (role_code IN ('SUPER_ADMIN', 'TENANT_ADMIN', 'SALES_MANAGER', 'SALES_ADVISOR', 'BOT_OPERATOR', 'READ_ONLY', 'INVENTORY_MANAGER'));
