"use client";
import { useAuth } from "@/lib/auth-context";
import { canManageInventory, canManageWebsite } from "@/lib/demo-permissions";
import { useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { Eye, ExternalLink, Globe, Save, Upload, Plus, ArrowUp, ArrowDown, Trash2, CheckCircle2 } from "lucide-react";
import { defaultWebsite, type WebsiteContent, type WebsiteState } from "@/lib/website-content";
import { demoCatalog, isLocalDemo, type DemoProperty } from "@/lib/demo-catalog";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";

type Json = string | number | boolean | null | Json[] | { [key: string]: Json };
const labels: Record<string,string> = { title:"Título",name:"Nombre",description:"Descripción",body:"Texto",eyebrow:"Texto superior",emphasis:"Texto destacado",enabled:"Mostrar en la web",label:"Texto",value:"Contenido",src:"Imagen",alt:"Descripción de la imagen",href:"Destino del enlace",media:"Imagen",referenceMedia:"Imagen de referencia",location:"Ubicación",type:"Tipo",status:"Estado",city:"Ciudad",address:"Dirección",commercialPhones:"Teléfonos comerciales",constructionPhone:"Teléfono de construcción",weekdayHours:"Horario de lunes a viernes",saturdayHours:"Horario del sábado",whatsappDisplay:"WhatsApp (texto visible)",whatsappPhone:"WhatsApp (solo números)",suffix:"Sufijo",image:"Imagen",buttonLabel:"Texto del botón",subtitle:"Subtítulo",greeting:"Saludo inicial",suggestions:"Preguntas sugeridas",knowledge:"Información adicional",showContact:"Mostrar solicitud de contacto",focusAreas:"Servicios",cta:"Texto de consulta" };
const button = "inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50";
const primary = "inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50";
const input = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 focus:outline-2 focus:outline-blue-500";
const webUrl = "http://127.0.0.1:3002/";
const clone = <T,>(value:T):T => JSON.parse(JSON.stringify(value));
const fieldLabel = (key:string) => labels[key] || key;

function ImageField({value,onChange,label}:{value:string;onChange:(value:string)=>void;label:string}) {
  const [error,setError]=useState("");
  return <div className="space-y-2"><label className="block text-sm font-medium">{label}<input className={input} value={value.startsWith("data:")?"Imagen cargada desde tu computadora":value} readOnly={value.startsWith("data:")} onChange={e=>onChange(e.target.value)} /></label>
    <label className={button}><Upload className="h-4 w-4"/>Cargar imagen<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={e=>{const file=e.target.files?.[0]; if(!file)return;if(file.size>2_000_000||!['image/png','image/jpeg','image/webp'].includes(file.type)){setError("Usá PNG, JPG o WebP de hasta 2 MB.");return;}const reader=new FileReader();reader.onload=()=>{onChange(String(reader.result));setError("");};reader.readAsDataURL(file);}} /></label>
    {value && <><button className={button} onClick={()=>onChange("")} type="button">Quitar imagen</button><img src={value.startsWith('/')?webUrl.slice(0,-1)+value:value} alt="Vista previa de la imagen" className="max-h-40 max-w-full rounded-lg object-contain" /></>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
  </div>;
}
function Fields({value,onChange,label="",path="",template}:{value:Json;onChange:(v:Json)=>void;label?:string;path?:string;template?:Json}) {
  if(typeof value==='boolean')return <label className="flex items-center gap-3 py-2 text-sm font-semibold"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)} className="h-4 w-4"/>{label}</label>;
  if(typeof value==='number')return <label className="block text-sm font-medium">{label}<input type="number" min="0" className={input} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
  if(typeof value==='string') {
    if(/(^|\.)(src|image)$/.test(path)||path.startsWith('assets.')&&path.endsWith('.value'))return <ImageField value={value} onChange={onChange} label={label}/>;
    return <label className="block text-sm font-medium">{label}{value.length>90||/(description|body|greeting|knowledge)$/.test(path)?<textarea rows={3} className={input} value={value} onChange={e=>onChange(e.target.value)}/>:<input className={input} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;
  }
  if(Array.isArray(value))return <div className="space-y-3"><h3 className="font-semibold">{label}</h3>{value.map((item,index)=>{const record=item&&typeof item==='object'&&!Array.isArray(item)?item:null;return <details key={index} className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer font-medium">{record?String(record.title||record.name||record.label||`Elemento ${index+1}`):String(item)||`Elemento ${index+1}`}{record?.enabled===false?' · Oculto':''}</summary>
      <div className="mt-4 space-y-3"><Fields value={item} template={Array.isArray(template)?template[0]:undefined} path={`${path}.${index}`} onChange={next=>onChange(value.map((old,i)=>i===index?next:old))}/>
      <div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={index===0} aria-label="Subir elemento" onClick={()=>{const next=[...value];[next[index-1],next[index]]=[next[index],next[index-1]];onChange(next);}}><ArrowUp className="h-4 w-4"/>Subir</button><button type="button" className={button} disabled={index===value.length-1} onClick={()=>{const next=[...value];[next[index+1],next[index]]=[next[index],next[index+1]];onChange(next);}}><ArrowDown className="h-4 w-4"/>Bajar</button><button type="button" className={button} onClick={()=>onChange(value.filter((_,i)=>i!==index))}><Trash2 className="h-4 w-4"/>Quitar del borrador</button></div></div></details>;})}
      <button className={button} type="button" onClick={()=>{const seed=Array.isArray(template)?template[0]:value[0];let item=seed===undefined?'':clone(seed);if(item&&typeof item==='object'&&!Array.isArray(item)){item={...item};if('id'in item)item.id=crypto.randomUUID();if('title'in item)item.title='Nuevo elemento';if('name'in item)item.name='Nuevo elemento';if('enabled'in item)item.enabled=true;}onChange([...value,item]);}}><Plus className="h-4 w-4"/>Agregar elemento</button>
    </div>;
  if(value&&typeof value==='object')return <div className="space-y-4">{Object.entries(value).filter(([key])=>!['id','intent','section','temporary','temporarySource','icon','group','position','imageLabel','referenceLabel'].includes(key)).map(([key,item])=><Fields key={key} value={item} label={fieldLabel(key)} path={`${path}.${key}`} template={template&&typeof template==='object'&&!Array.isArray(template)?template[key]:undefined} onChange={next=>onChange({...value,[key]:next})}/>)}</div>;
  return null;
}

function PropertiesManager() {
  const [properties,setProperties]=useState<DemoProperty[]>([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [editing,setEditing]=useState<DemoProperty|null>(null),[preview,setPreview]=useState<DemoProperty|null>(null);
  useEffect(()=>{let active=true;async function refresh(){try{const list=await demoCatalog() as DemoProperty[];if(active){setProperties(list);setError('');}}catch(reason){if(active)setError(String(reason));}}void refresh();const timer=setInterval(refresh,2500);return()=>{active=false;clearInterval(timer);};},[]);
  async function save(property:DemoProperty,patch:Partial<DemoProperty>){setBusy(true);setError('');try{const next=await demoCatalog('PATCH',{id:property.id,...patch}) as DemoProperty;setProperties(list=>list.map(p=>p.id===next.id?next:p));setEditing(null);setMessage(next.published?`${next.title}: guardada y visible en la web y en Bellomito.`:`${next.title}: oculta en la web y en Bellomito.`);}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo guardar.');}finally{setBusy(false);}}
  const shown=properties.filter(p=>(p.title+' '+p.city+' '+p.propertyType).toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Las mismas propiedades del panel y la web</h2><p className="mt-1 text-sm text-slate-600">Se cargan una sola vez. Guardar, publicar u ocultar se refleja automáticamente donde está Bellomito.</p></div><Link href="/admin/properties/new" className={primary}><Plus className="h-4 w-4"/>Cargar propiedad</Link></div>
    <label className="block max-w-lg text-sm font-medium">Buscar propiedad<input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre, ciudad o tipo"/></label>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-rose-800">{error}</p>}{message&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-900">{message}</p>}
    <p className="text-sm text-slate-500">{shown.length} propiedades · {properties.filter(p=>p.published).length} publicadas</p>
    <div className="space-y-3">{shown.map(p=><article key={p.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-slate-200 bg-white p-4"><div><h3 className="font-semibold">{p.title}</h3><p className="mt-1 text-sm text-slate-500">{p.propertyType} · {p.currency} {p.price.toLocaleString('es-AR')} · {p.city}</p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-xs font-semibold ${p.published?'bg-emerald-50 text-emerald-800':'bg-slate-100 text-slate-600'}`}>{p.published?'Visible en la web y Bellomito':'Oculta'}</span></div>
      <div className="flex flex-wrap gap-2"><button className={button} onClick={()=>setEditing(clone(p))}>Editar</button><button className={button} onClick={()=>setPreview(p)}><Eye className="h-4 w-4"/>Vista previa</button><button className={button} disabled={busy} onClick={()=>void save(p,{published:!p.published})}>{p.published?'Ocultar':'Publicar'}</button><a className={button} href={`${webUrl}?propiedad=${encodeURIComponent(p.id)}#catalogo-demo`} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/>{p.published?'Ver en la web':'Comprobar que está oculta'}</a></div>
    </article>)}</div>
    <Dialog open={!!editing} onOpenChange={open=>{if(!open)setEditing(null);}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-2xl"><DialogTitle>Editar propiedad</DialogTitle><DialogDescription>Los cambios se guardan en el catálogo compartido con la web de Bellomo.</DialogDescription>{editing&&<div className="space-y-4">{Object.entries({operation:{label:"Operación",choices:["sale","rent","temporal"]},propertyType:{label:"Tipo",choices:["Casa","Departamento","Lote","Local","Cochera"]},currency:{label:"Moneda",choices:["USD","ARS"]},status:{label:"Disponibilidad",choices:["available","reserved","sold"]}}).map(([key,field])=><label key={key} className="block text-sm font-medium">{field.label}<select className={input} value={String((editing as unknown as Record<string,unknown>)[key]||field.choices[0])} onChange={e=>setEditing({...editing,[key]:e.target.value})}>{field.choices.map(value=><option key={value} value={value}>{({sale:"Venta",rent:"Alquiler",temporal:"Temporal",available:"Disponible",reserved:"Reservada",sold:"Vendida"} as Record<string,string>)[value]||value}</option>)}</select></label>)}{['title','city','neighborhood','price','bedrooms','bathrooms','area_m2','description'].map(key=><label key={key} className="block text-sm font-medium">{({title:'Título',city:'Ciudad',neighborhood:'Barrio',price:'Precio',bedrooms:'Dormitorios',bathrooms:'Baños',area_m2:'Superficie (m²)',description:'Descripción'} as Record<string,string>)[key]}<input className={input} type={['price','bedrooms','bathrooms','area_m2'].includes(key)?'number':'text'} value={String((editing as unknown as Record<string,unknown>)[key]??'')} onChange={e=>setEditing({...editing,[key]:['price','bedrooms','bathrooms','area_m2'].includes(key)?Number(e.target.value):e.target.value})}/></label>)}<ImageField label="Foto de la propiedad" value={editing.mainImage||''} onChange={mainImage=>setEditing({...editing,mainImage})}/><button className={primary} disabled={busy} onClick={()=>{const {title,city,neighborhood,price,bedrooms,bathrooms,area_m2,description,mainImage,operation,propertyType,currency,status}=editing;void save(editing,{title,city,neighborhood,price,bedrooms,bathrooms,area_m2,description,mainImage,operation,propertyType,currency,status});}}>Guardar cambios</button>{error&&<p role="alert" className="text-red-700">{error}</p>}</div>}</DialogContent></Dialog>
    <Dialog open={!!preview} onOpenChange={open=>{if(!open)setPreview(null);}}><DialogContent className="sm:max-w-lg"><DialogTitle>Vista previa de la propiedad</DialogTitle><DialogDescription>Así se verá la información al publicarla.</DialogDescription>{preview&&<article className="rounded-xl border border-slate-200 bg-[#f4f1e9] p-5 text-[#123c4d]">{preview.mainImage&&<img src={preview.mainImage} alt={preview.title} className="mb-4 max-h-52 w-full rounded-lg object-cover"/>}<h3 className="text-xl font-semibold">{preview.title}</h3><p className="mt-2">{preview.neighborhood}, {preview.city}</p><p className="mt-4 text-2xl">{preview.currency} {preview.price.toLocaleString('es-AR')}</p><p className="mt-2">{preview.propertyType} · {preview.area_m2||'—'} m²</p><p className="mt-3">{preview.description}</p></article>}</DialogContent></Dialog>
  </div>;
}

export default function WebsiteAccess() {
  const { currentUser, isLoaded } = useAuth();
  if (!isLoaded) return <p>Cargando permisos…</p>;
  if (!canManageInventory(currentUser)) return <p role="alert">Tu perfil puede consultar propiedades, pero no administrarlas ni modificar la web.</p>;
  if (!canManageWebsite(currentUser)) return <div className="space-y-5"><h1 className="text-2xl font-bold">Web pública · Propiedades</h1><p>Tu permiso de inventario permite agregar, editar, publicar y ocultar propiedades. El contenido y Bellomito los administra Administración.</p><PropertiesManager/></div>;
  return <WebsiteEditor/>;
}
function WebsiteEditor() {
  const [state,setState]=useState<WebsiteState|null>(null),[content,setContent]=useState<WebsiteContent>(clone(defaultWebsite)),[tab,setTab]=useState('Propiedades'),[group,setGroup]=useState('heroSlides');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState(false),[textSearch,setTextSearch]=useState('');
  useEffect(()=>{if(!isLocalDemo)return;void fetch('/api/demo/site',{cache:'no-store'}).then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error);setState(result);setContent(result.draft);}).catch(reason=>setError(String(reason)));},[]);
  const dirty=state&&JSON.stringify(content)!==JSON.stringify(state.draft);
  const unpublished=state&&JSON.stringify(content)!==JSON.stringify(state.published);
  async function persist(action:'save'|'publish'|'discard',showPreview=false){if(!state)return;setBusy(true);setError('');try{const response=await fetch('/api/demo/site',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:state.revision,action,content})});const next=await response.json();if(!response.ok)throw Error(next.error);setState(next);setContent(next.draft);setNotice(action==='publish'?'Cambios publicados. La web de Bellomo se actualiza automáticamente.':action==='discard'?'Borrador restaurado a la última publicación.':'Borrador guardado. La web pública todavía no cambió.');if(showPreview)setPreview(true);}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo guardar.');}finally{setBusy(false);}}
  if(!isLocalDemo)return <p>Este módulo está disponible en la demo local.</p>;
  const update=(key:keyof WebsiteContent,value:Json)=>setContent({...content,[key]:value});
  const groups:Record<string,string>={heroSlides:'Portada e imágenes',bellomoProjects:'Desarrollos',constructionHighlights:'Construcción',propertyCategories:'Categorías',bellomoStats:'Cifras de Bellomo',navigation:'Menú de navegación',bellomoEditorialImages:'Imágenes de las secciones'};
  let editor:ReactNode=null;
  if(tab==='Propiedades')editor=<PropertiesManager/>;
  if(tab==='Secciones')editor=<div className="space-y-6"><h2 className="text-xl font-bold">Mostrar u ocultar partes de la web</h2><div className="grid gap-3 sm:grid-cols-2">{content.sections.map(section=><label key={section.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" checked={section.enabled} onChange={e=>setContent({...content,sections:content.sections.map(s=>s.id===section.id?{...s,enabled:e.target.checked}:s)})}/>{section.title}</label>)}</div><h2 className="text-xl font-bold">Agregar contenido a la web</h2><Fields label="Secciones adicionales" value={content.customSections as unknown as Json} template={[{id:'',title:'Nueva sección',body:'Escribí el contenido.',image:'',buttonLabel:'Ver más',href:'',enabled:true}]} path="customSections" onChange={v=>update('customSections',v)}/></div>;
  if(tab==='Contenido')editor=<div className="space-y-5"><div className="flex flex-wrap gap-2">{Object.entries(groups).map(([key,label])=><button className={group===key?primary:button} key={key} onClick={()=>setGroup(key)}>{label}</button>)}</div><Fields label={groups[group]} value={content.data[group as keyof typeof content.data] as unknown as Json} template={defaultWebsite.data[group as keyof typeof defaultWebsite.data] as unknown as Json} path={`data.${group}`} onChange={value=>setContent({...content,data:{...content.data,[group]:value}})}/></div>;
  if(tab==='Textos')editor=<div className="space-y-5"><h2 className="text-xl font-bold">Textos de la web</h2><input aria-label="Buscar texto" className={input} placeholder="Buscá el texto que ves en la web" value={textSearch} onChange={e=>setTextSearch(e.target.value)}/>{Object.entries(content.texts).filter(([,item])=>(item.label+' '+item.group+' '+item.value).toLocaleLowerCase().includes(textSearch.toLocaleLowerCase())).map(([key,item])=><label key={key} className="block rounded-xl border border-slate-200 p-4 text-sm"><span className="font-semibold">{item.group} · {item.label}</span><textarea className={input} rows={2} value={item.value} onChange={e=>setContent({...content,texts:{...content.texts,[key]:{...item,value:e.target.value}}})}/></label>)}</div>;
  if(tab==='Imágenes y enlaces')editor=<div className="space-y-6"><h2 className="text-xl font-bold">Marca e imágenes</h2><p className="text-sm text-slate-500">Las fotos de portada y desarrollos se editan en Contenido. Acá están las imágenes de marca y los enlaces del sitio.</p>{Object.entries(content.assets).map(([key,item])=><ImageField key={key} label={`${item.group} · ${item.label}`} value={item.value} onChange={value=>setContent({...content,assets:{...content.assets,[key]:{...item,value}}})}/>)}<h2 className="text-xl font-bold">Enlaces, redes sociales y teléfonos</h2>{Object.entries(content.links).map(([key,item])=><label key={key} className="block text-sm font-medium">{item.group} · {item.label}<input className={input} value={item.value} onChange={e=>setContent({...content,links:{...content.links,[key]:{...item,value:e.target.value}}})}/></label>)}</div>;
  if(tab==='Contacto')editor=<Fields value={content.data.bellomoContact as unknown as Json} path="data.bellomoContact" onChange={value=>setContent({...content,data:{...content.data,bellomoContact:value as typeof content.data.bellomoContact}})}/>;
  if(tab==='Bellomito')editor=<div className="space-y-4"><p className="rounded-xl bg-blue-50 p-4 text-sm text-blue-950">Bellomito consulta las mismas propiedades que cargás en el panel. No tenés que cargarlas de nuevo acá.</p><Fields value={content.bot as unknown as Json} template={defaultWebsite.bot as unknown as Json} path="bot" onChange={v=>update('bot',v)}/></div>;
  return <div className="mx-auto max-w-6xl space-y-5 pb-12"><header className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-3 text-3xl font-bold text-slate-900"><Globe className="h-7 w-7 text-blue-600"/>Web pública</h1><p className="mt-2 text-sm text-slate-600">Toda la web de Bellomo, donde está Bellomito, se administra desde acá.</p></div><span className="rounded-full bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800">Demo local</span></div><div className="mt-5 flex flex-wrap gap-2"><button className={button} disabled={busy||!state} onClick={()=>void persist('save',true)}><Eye className="h-4 w-4"/>Vista previa</button><a className={button} href={webUrl} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/>Ver web</a><button className={button} disabled={busy||!state||!dirty} onClick={()=>void persist('save')}><Save className="h-4 w-4"/>Guardar borrador</button><button className={primary} disabled={busy||!state} onClick={()=>void persist('publish')}><CheckCircle2 className="h-4 w-4"/>{busy?'Guardando…':'Publicar cambios'}</button><button className={button} disabled={busy||!state||!unpublished} onClick={()=>void persist('discard')}>Descartar borrador</button></div><p className="mt-3 text-xs text-slate-500">{dirty?'Tenés cambios sin guardar.':unpublished?'Borrador guardado, pendiente de publicar.':'Contenido publicado al día.'} {state?.publishedAt?`Última publicación: ${new Date(state.publishedAt).toLocaleString('es-AR', { timeZone: 'America/Argentina/Buenos_Aires' })}.`:''} Las propiedades se sincronizan al guardarlas.</p></header>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-900">{notice}</p>}
    <nav aria-label="Administración de la web" className="flex flex-wrap gap-2">{['Propiedades','Secciones','Contenido','Textos','Imágenes y enlaces','Contacto','Bellomito'].map(item=><button key={item} aria-pressed={tab===item} className={tab===item?primary:button} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 text-slate-900 sm:p-6">{state?editor:<p role="status">Cargando administración de la web…</p>}</section>
    <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="h-[90vh] sm:max-w-[95vw]"><DialogTitle>Vista previa de la web de Bellomo</DialogTitle><DialogDescription>Este borrador todavía no está publicado. Las propiedades muestran su estado actual.</DialogDescription><iframe title="Vista previa de Bellomo" src={`${webUrl}?preview=1`} className="h-[75vh] w-full rounded-lg border"/></DialogContent></Dialog>
  </div>;
}
